services:
  - type: web
    name: lstracker-bot
    env: node
    buildCommand: pnpm install && pnpm build:render
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production

